const BLOG = require('./blog.config')

const normalizeSiteUrl = url => {
  if (!url) return ''
  const value = String(url).trim().replace(/\/+$/, '')
  if (!value) return ''
  if (/^https?:\/\//i.test(value)) return value
  return `https://${value}`
}

const siteUrl =
  normalizeSiteUrl(BLOG.LINK) ||
  normalizeSiteUrl(process.env.VERCEL_PROJECT_PRODUCTION_URL) ||
  normalizeSiteUrl(process.env.VERCEL_URL) ||
  'https://deeprouter.org'

/**
 * 通常没啥用，sitemap交给 /pages/sitemap.xml.js 动态生成
 */
module.exports = {
  siteUrl,
  changefreq: 'daily',
  priority: 0.7,
  // robots.txt is generated by lib/utils/robots.txt.js so GEO/AI bot policies
  // are preserved after postbuild.
  generateRobotsTxt: false,
  exclude: [
    '/404',
    '/500',
    '/search',
    '/search/*',
    '/llms.txt',
    '/sitemap.xml'
  ],
  sitemapSize: 7000
  // ...other options
  // https://github.com/iamvishnusankar/next-sitemap#configuration-options
}
